name: Build and package
on: push

jobs:
  build-osx:
    name: Build for macos-10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r dependencies.txt
      - name: package binary
        run: |
          pyinstaller --clean --onefile --windowed pyinstaller/pyinstaller_osx.spec
          ls -lR dist
      - name: publish binary
        uses: actions/upload-artifact@master
        with:
          name: formula_macosx.app
          path: dist/formula.app
  build-windows:
    name: Build for windows-2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r dependencies.txt
      - name: package binary
        run: |
          python -m PyInstaller --clean pyinstaller/pyinstaller.spec
      - name: publish binary
        uses: actions/upload-artifact@master
        with:
          name: formula_windows
          path: dist/formula.exe
  build-ubuntu:
    name: Build for ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install apt dependencies
        run: |
          sudo apt update
          sudo apt install -y $(cat apt_dependencies.txt)
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r dependencies.txt
      - name: package binary
        run: |
          pyinstaller --clean pyinstaller/pyinstaller.spec
          mv dist/formula dist/formula_ubuntu18
      - name: publish binary
        uses: actions/upload-artifact@master
        with:
          name: formula_ubuntu18
          path: dist/formula_ubuntu18
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/release')
    name: Publish release to github
    runs-on: ubuntu-18.04
    needs: [build-osx, build-windows, build-ubuntu]
    steps:
      - name: Download osx artifact
        uses: actions/download-artifact@v1
        with:
          name: formula_macosx.app
      - name: Download windows artifact
        uses: actions/download-artifact@v1
        with:
          name: formula_windows
      - name: Download ubuntu18 artifact
        uses: actions/download-artifact@v1
        with:
          name: formula_ubuntu18
      - name: Trimming tag
        id: trimmer
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/release/}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.trimmer.outputs.tag }}
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "formula_macosx/formula_macosx,formula_windows/formula.exe,formula_ubuntu18/formula_ubuntu18"
