name: Build windows
on: push

jobs:
  build:
    name: Build for windows-2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r dependencies.txt
      - name: package binary
        run: |
          python -m PyInstaller --clean pyinstaller.spec
      - name: publish binary
        uses: actions/upload-artifact@master
        with:
          name: formula_windows
          path: dist/formula.exe
