name: Build linux
on: push

jobs:
  build:
    name: Build for ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install apt dependencies
        run: |
          apt install $(cat apt_dependencies)
      - name: install apt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies.txt
